version: 2.1
orbs:
  node: circleci/node@4.0.0
  slack: circleci/slack@3.4.2
jobs:
  test:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run build
      - run:
          command: npm run test -- --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - slack/status:
          only_for_branches: master

workflows:
  workflow:
    jobs:
      - test
